/**
 * Liste des pays pour listes déroulantes (facturation, collaborations, etc.)
 * Ordre : France en premier, puis pays francophones / UE, puis alphabétique.
 */
export const LISTE_PAYS: string[] = [
  "France",
  "Belgique",
  "Suisse",
  "Luxembourg",
  "Monaco",
  "Allemagne",
  "Espagne",
  "Italie",
  "Portugal",
  "Pays-Bas",
  "Royaume-Uni",
  "Irlande",
  "Autriche",
  "Pologne",
  "Roumanie",
  "Grèce",
  "République tchèque",
  "Hongrie",
  "Suède",
  "Danemark",
  "Finlande",
  "Norvège",
  "Bulgarie",
  "Croatie",
  "Slovaquie",
  "Slovénie",
  "Estonie",
  "Lettonie",
  "Lituanie",
  "Chypre",
  "Malte",
  "États-Unis",
  "Canada",
  "Maroc",
  "Algérie",
  "Tunisie",
  "Sénégal",
  "Côte d'Ivoire",
  "Cameroun",
  "Mali",
  "Bénin",
  "Togo",
  "Burkina Faso",
  "Niger",
  "Gabon",
  "Congo",
  "Madagascar",
  "Maurice",
  "Île Maurice",
  "Réunion",
  "Guadeloupe",
  "Martinique",
  "Guyane française",
  "Mayotte",
  "Nouvelle-Calédonie",
  "Polynésie française",
  "Saint-Martin",
  "Saint-Barthélemy",
  "Japon",
  "Chine",
  "Corée du Sud",
  "Inde",
  "Australie",
  "Brésil",
  "Mexique",
  "Argentine",
  "Chili",
  "Colombie",
  "Pérou",
  "Afrique du Sud",
  "Égypte",
  "Israël",
  "Émirats arabes unis",
  "Qatar",
  "Arabie saoudite",
  "Turquie",
  "Russie",
  "Ukraine",
  "Indonésie",
  "Thaïlande",
  "Vietnam",
  "Singapour",
  "Malaisie",
  "Philippines",
  "Nouvelle-Zélande",
  "Autre",
];
